name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on:
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodby
        run: echo "done -bye!"
